### ISSUE TITLE
Error in Discover in Opensearch's integration

### ISSUE THREAD

**Issue by mcasas993** [wazuh/wazuh-indexer#448]
## Description

When we tested the integrations, [we found an error](https://github.com/wazuh/wazuh-indexer/issues/445#issuecomment-2400479621) in Discover section of Opensearch. The Discover doesn't show anything and expose this message:

```
illegal_argument_exception
Field [data.osquery.calendarTime] of type [keyword] does not support custom formats
Error: Bad Request
    at fetch_Fetch.fetchResponse (https://localhost:5602/7969/bundles/core/core.entry.js:15:392113)
    at async interceptResponse (https://localhost:5602/7969/bundles/core/core.entry.js:15:386867)
    at async https://localhost:5602/7969/bundles/core/core.entry.js:15:389834

```

**Comment by QU3B1M** [comment]
### Update report

For what I see on the [wazuh-dashboard-plugins code](https://github.com/wazuh/wazuh-dashboard-plugins/blob/052d4648aef3eee48d02780430069fffc2abcd20/plugins/main/public/utils/known-fields.js#L2030), the field `calendarTime` is expected to be a string, I suspect that (being optimistic) the error could be that the time is being expressed with an Integer. 

Currently working on reproducing the error correctly analyze the root cause and the possible fix.

**Comment by QU3B1M** [comment]
The field's type value defined on the file `integrations/opensearch/dashboards.ndjson` that is used on the OpenSearch integration is incorrect causing the reported error to appear when the Discover module is accessed.

While fixing the type of the field `data.osquery.calendarTime` I've found that the field's type for `data.virustotal.scan_date` is also incorrect, now both are fixed.

**Comment by AlexRuiz7** [comment]
We'll plan a new release of the [OpenSearch integration dashboards](https://documentation.wazuh.com/current/integrations-guide/opensearch/index.html#opensearch-dashboards).
